EXPERIMENT:
  NAME: ""
  TAG: "kd,lemma,ResNet50,MobileNetV2,2,9"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "KD"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV2"
LEMMA:
  ENABLE: True
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  

