EXPERIMENT:
  NAME: ""
  TAG: "kd,lemma,vgg13,vgg8,2,9"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "KD"
  TEACHER: "vgg13"
  STUDENT: "vgg8"
LEMMA:
  ENABLE: True
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  

