MODEL:
  TYPE: PVTv2
  NUM_CLASSES: 100
TRANSFORMER:
  PATCH_SIZE: [7, 3, 3, 3]
  PATCH_STRIDE: [4, 2, 2, 2]
  HIDDEN_DIM: [32, 64, 160, 256]
  DEPTH: [2, 2, 2, 2]
  NUM_HEADS: [1, 2, 5, 8]
  MLP_RATIO: [8, 8, 4, 4]
  DROP_RATE: 0.0
  DROP_PATH_RATE: 0.1
  ATTENTION_DROP_RATE: 0.0
PVT:
  SR_RATIO: [8, 4, 2, 1]
OPTIM:
  OPTIMIZER: adamw
  BASE_LR: 5.0e-4
  MIN_LR: 5.0e-6
  LR_POLICY: cos
  MAX_EPOCH: 300
  WEIGHT_DECAY: 0.05
  WARMUP_FACTOR: 0.001
  WARMUP_EPOCHS: 20
TRAIN:
  DATASET: cifar100
  SPLIT: train
  BATCH_SIZE: 128
TEST:
  DATASET: cifar100
  SPLIT: test
  BATCH_SIZE: 200
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: False
